#!/bin/bash
# File Organization Script for kody-w/base
# Generated by File Organizer Agent

echo "Organizing repository files..."

# Move gameboy-emulator.html to games
mv "gameboy-emulator.html" "apps/games/gameboy-emulator.html"

# Move task-manager.html to productivity
mv "task-manager.html" "apps/productivity/task-manager.html"

# Move code-editor.html to development
mv "code-editor.html" "apps/development/code-editor.html"

echo "Organization complete!"
echo "Don't forget to commit and push your changes:"
echo "git add ."
echo "git commit -m 'Reorganize files into categories'"
echo "git push"
